/**
 * @NApiVersion 2.x
 * @NScriptType Suitelet
 */
define(
		[ 'N/ui/serverWidget', 'N/search' ],
		function(ui, search) {
			function onRequest(context) {
				if (context.request.method === 'GET') {
					var parameters = context.request.parameters;
					var plId = parameters.plId;
					var form = initForm(ui);
					context.response.writePage(form);
				} else {
					// var loginName = context.request.custpage_loginname;
					// var loginPaw = parameters.custpage_loginpsw;
					// if (condition) {
					//				
					// }
				}

			}

			function initForm(ui) {
				var form = ui.createForm({
					title : 'Project List Item'
				});
				 form.clientScriptFileId = 550;
				form.addField({
					id : 'custpage_pllist',
					type : ui.FieldType.INLINEHTML,
					label : 'Project List'
				}).defaultValue = getHtml();
				form.addButton({
					id : 'custpage_refresh',
					label : 'Refresh',
					functionName : 'refresh()'
				});
				return form;
			}

			function getHtml() {
				var html = "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n"
						+ "<html>\r\n"
						+ "<head>\r\n"
						+ "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n"
						+ "<title>css+html实现固定表头</title>\r\n"
						+ "<style type=\"text/css\">\r\n"
						+ "#scrollTable {\r\n"
						+ "	width: 100%;\r\n"
//						+ "	border: 1px solid #EB8; /*table没有外围的border，只有内部的td或th有border*/\r\n"
						//+ "	background: #FF8C00;\r\n"
						+ "}\r\n"
						+ "#scrollTable table {\r\n"
						+ "	border-collapse: collapse; /*统一设置两个table为细线表格*/\r\n"
						+ "}\r\n"
						+ "/*表头 div的第一个子元素**/\r\n"
						+ "#scrollTable table.thead {\r\n"
						+ "	width: 100%;\r\n"
						+ "}\r\n"
						+ "/*表头*/\r\n"
						+ "#scrollTable table.thead th {\r\n"
						+ "	border: 1px solid;\r\n"
//						+ "	border: 1px solid #EB8;\r\n"
//						+ "	border-right: #C96;\r\n"
//						+ "	color: #666666;\r\n"
						+ "	background: grey; /*灰色*/\r\n"
						+ "}\r\n"
						+ "/*能带滚动条的表身*/\r\n"
						+ "/*div的第二个子元素*/\r\n"
						+ "#scrollTable div {\r\n"
						+ "	width: 100%;\r\n"
						+ "	height: 300px;\r\n"
						+ "	overflow: auto; /*必需*/\r\n"
//						+ "	scrollbar-face-color: #EB8; /*那三个小矩形的背景色*/\r\n"
//						+ "	scrollbar-base-color: #ece9d8; /*那三个小矩形的前景色*/\r\n"
//						+ "	scrollbar-arrow-color: #FF8C00; /*上下按钮里三角箭头的颜色*/\r\n"
//						+ "	scrollbar-track-color: #ece9d8; /*滚动条的那个活动块所在的矩形的背景色*/\r\n"
//						+ "	scrollbar-highlight-color: #800040; /*那三个小矩形左上padding的颜色*/\r\n"
//						+ "	scrollbar-shadow-color: #800040; /*那三个小矩形右下padding的颜色*/\r\n"
//						+ "	scrollbar-3dlight-color: #EB8; /*那三个小矩形左上border的颜色*/\r\n"
//						+ "	scrollbar-darkshadow-Color: #EB8; /*那三个小矩形右下border的颜色*/\r\n"
						+ "}\r\n"
						+ "/*能带滚动条的表身的正体*/\r\n"
						+ "#scrollTable table.tbody {\r\n"
						+ "	width: 100%;\r\n"
						+ "	border: 1px solid;\r\n"
//						+ "	border: 1px solid #C96;\r\n"
//						+ "	border-right: #B74;\r\n"
//						+ "	color: #666666;\r\n"
//						+ "	background: #ECE9D8;\r\n"
						+ "}\r\n"
						+ "/*能带滚动条的表身的格子*/\r\n"
						+ "#scrollTable table.tbody td {\r\n"
						+ "	border: 1px solid;\r\n"
//						+ "	border: 1px solid #C96;\r\n"
						+ "}\r\n"
						+ "</style>\r\n"
						+ "</head>\r\n"
						+ "<body>\r\n"
						+ "	<div id=\"scrollTable\">\r\n"
						+ "		<table class=\"thead\">\r\n"
						+ "			<col width=\"170px\"></col>\r\n"
						+ "			<col width=\"170px\"></col>\r\n"
						+ "			<col width=\"170px\"></col>\r\n"
						+ "			<col></col>\r\n"
						+ "			<tbody>\r\n"
						+ "				<tr>\r\n"
						+ "					<th>名称</th>\r\n"
						+ "					<th>语法</th>\r\n"
						+ "					<th>说明</th>\r\n"
						+ "					<th>例子</th>\r\n"
						+ "				</tr>\r\n"
						+ "			</tbody>\r\n"
						+ "		</table>\r\n"
						+ "		<div>\r\n"
						+ "			<table class=\"tbody\">\r\n"
						+ "				<col width=\"170px\"></col>\r\n"
						+ "				<col width=\"170px\"></col>\r\n"
						+ "				<col width=\"170px\"></col>\r\n"
						+ "				<col></col>\r\n"
						+ "				<tbody>\r\n"
						+ "					<tr>\r\n"
						+ "						<td><div id='1' contenteditable=\"true\" style = 'height:100%'>这是一段可编辑的段落。请试着编辑该文</div></td>\r\n"
						+ "						<td><div contenteditable=\"true\" style = 'height:100%'>这是一段可编辑的段落。请试着编辑该文</div></td>\r\n"
						+ "						<td><div contenteditable=\"true\" style = 'height:100%'>这是一段可编辑的段落。请试着编辑该文</div></td>\r\n"
						+ "						<td><div contenteditable=\"true\" style = 'height:100%'>这是一段可编辑的段落。请试着编辑该文</div></td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "					<tr>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "						<td>1</td>\r\n"
						+ "					</tr>\r\n"
						+ "				</tbody>\r\n"
						+ "			</table>\r\n"
						+ "		</div>\r\n"
						+ "	</div>\r\n"
						+ "</body>\r\n"
						+ "</html>\r\n" + "";
				return html;
			}
			return {
				onRequest : onRequest
			};
		});